server:
  port: 8080

spring:
  application:
    name: product-service
  
  data:
    mongodb:
      host: ${MONGODB_HOST:mongodb}
      port: ${MONGODB_PORT:27017}
      database: ${MONGODB_DATABASE:ecommerce}
  
  redis:
    host: ${REDIS_HOST:redis}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  
  cache:
    type: redis
    redis:
      time-to-live: 600000 # 10 minutes

logging:
  level:
    com.ecommerce.product: DEBUG
    org.springframework.data.mongodb: DEBUG
    org.springframework.cache: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  health:
    redis:
      enabled: false
    mongo:
      enabled: true

# Custom application properties
app:
  cache:
    default-ttl: 600 # 10 minutes
    product-ttl: 1800 # 30 minutes
